### ISSUE TITLE
Empty reports after test run

### ISSUE THREAD

**Issue by NuclearPenguin** [allure-framework/allure-maven-plugin#14]
Hi, I have a problem.It does not generate the results file in allure-results
As a result of going to an empty report after tests

When changing allure.version on 1.4.14, I get an error at the start of tests

```
Running TestSuite
java.lang.reflect.UndeclaredThrowableException
	at sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	... 4 more
Caused by: java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider ru.yandex.qatools.allure.testng.AllureTestListener not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:365)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:945)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:895)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:149)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:95)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	... 9 more
[ERROR] There are test failures.</code>
```

**pom.xml**
```xml
    <groupId>com.ats</groupId>
    <artifactId>vis-web-testing</artifactId>
    <version>0.0.1</version>

    <properties>
        <surefire.version>2.8.1</surefire.version>
        <allure.version>1.3.9</allure.version>
        <aspectj.version>1.8.5</aspectj.version>
        <encoding>UTF-8</encoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>nl.javadude.assumeng</groupId>
            <artifactId>assumeng</artifactId>
            <version>RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.cthul</groupId>
            <artifactId>cthul-matchers</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.matchers</groupId>
            <artifactId>webdriver-matchers</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.matchers</groupId>
            <artifactId>matcher-decorators</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.matchers</groupId>
            <artifactId>collection-matchers</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>3.0</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>${allure.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-java-aspects</artifactId>
            <version>1.4.11</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.42.2</version>
        </dependency>
        <dependency>
            <groupId>ru.stqa.selenium</groupId>
            <artifactId>webdriver-factory</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.htmlelements</groupId>
            <artifactId>htmlelements-java</artifactId>
            <version>1.13</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.9</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.9</version>
        </dependency>
        <dependency>
            <groupId>org.docx4j</groupId>
            <artifactId>docx4j</artifactId>
            <version>2.8.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>
                <configuration>
                    <groups>new</groups>
                    <testFailureIgnore>true</testFailureIgnore>
                    <systemPropertyVariables>
                        <webdriver.chrome.driver>src/test/resources/chromedriver.exe</webdriver.chrome.driver>
                    </systemPropertyVariables>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
                    </argLine>
                    <systemProperties>
                        <property>
                            <name>aj.weaving.verbose</name>
                            <value>true</value>
                        </property>
                    </systemProperties>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sources>
                        <source>
                            <basedir>src</basedir>
                            <includes>
                                <include>**/*.java</include>
                            </includes>
                        </source>
                    </sources>
                    <complianceLevel>1.7</complianceLevel>
                    <outxml>false</outxml>
                    <verbose>true</verbose>
                    <showWeaveInfo>true</showWeaveInfo>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.mortbay.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>8.1.16.v20140903</version>
                <configuration>
                    <stopKey>stopjetty</stopKey>
                    <stopPort>8079</stopPort>
                    <webAppSourceDirectory>${project.build.directory}/site/allure-maven-plugin</webAppSourceDirectory>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <outputDirectory>${project.build.directory}/site</outputDirectory>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <resultsPattern>${project.build.directory}/allure-results</resultsPattern>
                    <reportVersion>1.3.9</reportVersion>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
</project>
```
Use Maven 3.3.3

**Comment by vania-pooh** [comment]
Does https://github.com/allure-examples/allure-testng-example with new Allure version as dependency works for you?

**Comment by NuclearPenguin** [comment]
What do you mean by "works for me"? Test example works, but what I do at do not really understand.

**Comment by NuclearPenguin** [comment]
Вообщем, генерируется пустой отчёт при текущем моём pom.xml хотя никаких ошибок нету, и тесты проходят. просто result.xml не создаётся. Если я поменяю версию allure-testng-adaptor на более новую то у меня валится ошибка.

**Comment by baev** [comment]
@NuclearPenguin see https://github.com/allure-framework/allure-maven-plugin/issues/13 

Downgrade your testNg version to `6.8.*`

**Comment by NuclearPenguin** [comment]
Fuck yeah, it worked, thanks
